name: apiverve_agecalculator
description: Age Calculator is a simple tool for calculating age from the date of birth. It returns the calculated age based on the date of birth provided.
version: 1.1.13
homepage: https://apiverve.com/marketplace/agecalculator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/agecalculator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
